# Generated by Django 5.1.5 on 2025-01-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_updated_at_post_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('age', models.IntegerField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150, null=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('visit_date', models.DateField(default='2025-01-16')),
            ],
        ),
    ]
