# Generated by Django 5.1.5 on 2025-01-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
