# Generated by Django 5.1.5 on 2025-01-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='visit_date',
            field=models.DateField(default='2025-01-16'),
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
