# Generated by Django 5.1.5 on 2025-01-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_patients_visit_date_alter_visit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='visit_date',
            field=models.DateField(default='2025-01-18', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default='2025-01-18'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='photos/%Y%m%d')),
                ('add_at', models.DateField(default='%Y-%m-%d')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.patients')),
            ],
        ),
    ]
