# Generated by Django 5.1.5 on 2025-01-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_patients_visit_date_alter_visit_date_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='add_at',
            field=models.DateField(default='2025-01-18'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.FileField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
