# Generated by Django 5.1.5 on 2025-01-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_photo_add_at_alter_photo_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
