# Generated by Django 5.1.5 on 2025-01-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_visit_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(null=True, upload_to='pdfs/%Y/%m/%d'),
        ),
    ]
