# Generated by Django 5.1.5 on 2025-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_photo_visit_alter_photo_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='visit_date',
            field=models.DateField(default='2025-01-20', null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='add_at',
            field=models.DateField(default='2025-01-20'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(default='2025-01-20'),
        ),
    ]
